name: ansible-test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/ohioit/github

    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
        with:
          path: ansible_collections/ohioit/github

      - name: Set up Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9

      - name: Install Ansible
        run: pip install ansible
        
      - name: Install PyGithub
        run: pip install PyGithub

      - name: Configure integration test run
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION_NAME: senior-design-21-22
        run: |
          ./tests/utils/render.sh \
            tests/integration/integration_config.yaml.template \
            > tests/integration/integration_config.yml
   
      - name: Run the integration tests
        run: ansible-test integration --python 3.6

      - name: Perform sanity testing with ansible-test on module files
        run: ansible-test sanity --python 3.6 plugins/modules/*
          
      - name: Perform unit testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.11
          pre-test-cmd: echo This runs before the ansible-test invocation
          python-version: 3.6
          target-python-version: 3.6
          testing-type: units
          test-deps: >-
            ansible.netcommon
            ansible.utils
