

name: ansible-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the this branch
  push:
    branches: [ fix-testing-workflow ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/senior-design-21-22/ansible-collection-github

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
        with:
          path: ansible_collections/senior-design-21-22/ansible-collection-github

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Ansible
        run: pip install ansible

      - name: Configure integration test run
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION_NAME: senior-design-21-22
        run: |
          ./tests/utils/render.sh \
            tests/integration/integration_config.yaml.template \
            > tests/integration/integration_config.yaml
            
#       - name: Install the ansible collection
#         run: ansible-galaxy collection install . --force
   
      - name: Run the integration tests
        run: ansible-test integration --python 3.7

      # - name: Perform sanity testing with ansible-test
      #   uses: ansible-community/ansible-test-gh-action@release/v1
      #   with:
      #     ansible-core-version: stable-2.11
      #     testing-type: sanity
          
      # - name: Perform unit testing with ansible-test
      #   uses: ansible-community/ansible-test-gh-action@release/v1
      #   with:
      #     ansible-core-version: stable-2.11
      #     pre-test-cmd: echo This runs before the ansible-test invocation
      #     python-version: 3.9
      #     target-python-version: 3.9
      #     testing-type: units
      #     test-deps: >-
      #       ansible.netcommon
      #       ansible.utils
